server:
  port: 8080 
  servlet:
    context-path: / 
    encoding:
      charset: UTF-8
      enabled: true
      force: true
     
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/roomescape?serverTimeZone=Asia/Seoul
    username: roomescape
    password: room1234

       
  mvc:
    view:
      prefix: /templates/
      suffix: .mustache